import sqlite3

conn = sqlite3.connect('backend/migrations/reviews.db')
c = conn.cursor()

# Drop and recreate the global_keywords and brand_keywords tables
c.execute('DROP TABLE IF EXISTS global_keywords')
c.execute('CREATE TABLE global_keywords (category TEXT PRIMARY KEY, keywords TEXT NOT NULL)')
c.execute('DROP TABLE IF EXISTS brand_keywords')
c.execute('CREATE TABLE brand_keywords (id INTEGER PRIMARY KEY AUTOINCREMENT, brand_id TEXT NOT NULL, category TEXT NOT NULL, keywords TEXT NOT NULL)')

# Insert required categories with comprehensive keywords into global_keywords
categories_keywords = [
    ('Sizing & Fit Mentions', '["size", "fit", "small", "large", "tight", "loose", "true to size", "runs small", "runs large", "size up", "size down", "too big", "too small", "fitted", "fitting", "oversized", "undersized", "baggy", "snug", "perfect fit", "ill fitting", "fit well", "fit perfectly", "fit issues", "fit problem", "fit great", "fit bad", "fit amazing", "fit awful", "fit fine", "fit ok", "fit perfect", "fit poor", "fit right", "fit wrong", "fit as expected", "fit as described", "fit as advertised"]'),
    ('Model Reference', '["model", "model size", "model height", "model weight", "model reference", "model is wearing", "model stats", "model measurements", "model info", "model\'s size", "model\'s height", "model\'s weight", "as seen on model", "model photo", "model picture", "model details", "model description"]'),
    ('Product Quality', '["quality", "material", "fabric", "cheap", "durable", "well made", "poor quality", "defective", "broken", "tear", "rip", "stitching", "seam", "thread", "wear and tear", "last long", "fall apart", "shrink", "fade", "wash well", "wash bad", "pilling", "scratchy", "soft", "comfortable", "uncomfortable", "sturdy", "flimsy", "high quality", "low quality", "premium", "luxury", "inferior", "superior", "excellent quality", "bad quality", "good quality", "bad material", "good material", "nice fabric", "bad fabric"]'),
    ('Length & Body Suitability', '["length", "short", "long", "crop", "cropped", "tall", "petite", "sleeve length", "inseam", "rise", "waist", "hips", "shoulder", "bust", "body type", "body shape", "suitable for", "not for", "fit my body", "fit my shape", "fit my height", "fit my waist", "fit my hips", "fit my bust", "too short", "too long", "just right length", "perfect length", "awkward length", "body proportion", "proportionate", "disproportionate", "fit my proportions"]'),
    ('Returns & Exchanges', '["return", "refund", "exchange", "store credit", "money back", "send back", "return policy", "exchange policy", "easy return", "difficult return", "return process", "refund process", "got my money back", "did not get refund", "return label", "return shipping", "return fee", "restocking fee", "return experience", "exchange experience", "refund experience", "return request", "exchange request", "refund request", "return denied", "refund denied", "exchange denied"]'),
    ('Customer Service & Shipping', '["customer service", "support", "help", "assistant", "representative", "agent", "staff", "team", "service", "assistance", "helpful", "unhelpful", "rude", "polite", "friendly", "professional", "knowledgeable", "ignored", "responsive", "slow", "quick", "efficient", "inefficient", "resolved", "unresolved", "satisfied", "unsatisfied", "complaint", "inquiry", "question", "response", "reply", "contact", "call", "email", "chat", "live chat", "phone", "hotline", "helpline", "shipping", "delivery", "delivered", "arrived", "arrival", "shipped", "dispatch", "dispatched", "tracking", "track", "package", "parcel", "postage", "post", "courier", "carrier", "fast", "slow", "quick", "delayed", "late", "on time", "express", "standard", "free shipping", "shipping cost", "postage cost", "delivery fee", "tracking number", "order status", "in transit", "out for delivery", "received", "signature", "left at door", "neighbor", "mailbox", "post office", "collection", "pickup"]'),
    ('Custom Category', '[]'),
]
for category, keywords in categories_keywords:
    c.execute('INSERT INTO global_keywords (category, keywords) VALUES (?, ?)', (category, keywords))

# Insert comprehensive brand-specific keywords for Missacc
brand = 'Missacc'
brand_categories_keywords = [
    ('Sizing & Fit Mentions', '["size", "fit", "petite", "plus size", "slim fit", "oversized", "bodycon", "loose fit", "tight fit", "baggy", "snug", "true to size", "runs small", "runs large", "size up", "size down", "too big", "too small", "fitted", "fitting", "perfect fit", "ill fitting", "fit well", "fit perfectly", "fit issues", "fit problem", "fit great", "fit bad", "fit amazing", "fit awful", "fit fine", "fit ok", "fit perfect", "fit poor", "fit right", "fit wrong", "fit as expected", "fit as described", "fit as advertised", "waist too tight", "hips too loose", "shoulders too broad", "arms too short", "arms too long", "sleeves too tight", "sleeves too loose", "neck too tight", "neck too loose"]'),
    ('Model Reference', '["model", "model size", "model height", "model weight", "model reference", "model is wearing", "model stats", "model measurements", "model info", "model\'s size", "model\'s height", "model\'s weight", "as seen on model", "model photo", "model picture", "model details", "model description", "model fit", "model body type", "model body shape"]'),
    ('Product Quality', '["quality", "material", "fabric", "cheap", "durable", "well made", "poor quality", "defective", "broken", "tear", "rip", "stitching", "seam", "thread", "wear and tear", "last long", "fall apart", "shrink", "fade", "wash well", "wash bad", "pilling", "scratchy", "soft", "comfortable", "uncomfortable", "sturdy", "flimsy", "high quality", "low quality", "premium", "luxury", "inferior", "superior", "excellent quality", "bad quality", "good quality", "bad material", "good material", "nice fabric", "bad fabric", "fabric pills", "fabric stretches", "fabric shrinks", "fabric fades", "fabric tears", "fabric rips", "fabric softens", "fabric hardens", "fabric wrinkles", "fabric creases"]'),
    ('Length & Body Suitability', '["length", "short", "long", "crop", "cropped", "tall", "petite", "sleeve length", "inseam", "rise", "waist", "hips", "shoulder", "bust", "body type", "body shape", "suitable for", "not for", "fit my body", "fit my shape", "fit my height", "fit my waist", "fit my hips", "fit my bust", "too short", "too long", "just right length", "perfect length", "awkward length", "body proportion", "proportionate", "disproportionate", "fit my proportions", "torso too short", "torso too long", "legs too short", "legs too long", "arms too short", "arms too long"]'),
    ('Returns & Exchanges', '["return", "refund", "exchange", "store credit", "money back", "send back", "return policy", "exchange policy", "easy return", "difficult return", "return process", "refund process", "got my money back", "did not get refund", "return label", "return shipping", "return fee", "restocking fee", "return experience", "exchange experience", "refund experience", "return request", "exchange request", "refund request", "return denied", "refund denied", "exchange denied", "return window", "exchange window", "refund window", "return instructions", "exchange instructions", "refund instructions"]'),
    ('Customer Service & Shipping', '["customer service", "support", "help", "assistant", "representative", "agent", "staff", "team", "service", "assistance", "helpful", "unhelpful", "rude", "polite", "friendly", "professional", "knowledgeable", "ignored", "responsive", "slow", "quick", "efficient", "inefficient", "resolved", "unresolved", "satisfied", "unsatisfied", "complaint", "inquiry", "question", "response", "reply", "contact", "call", "email", "chat", "live chat", "phone", "hotline", "helpline", "shipping", "delivery", "delivered", "arrived", "arrival", "shipped", "dispatch", "dispatched", "tracking", "track", "package", "parcel", "postage", "post", "courier", "carrier", "fast", "slow", "quick", "delayed", "late", "on time", "express", "standard", "free shipping", "shipping cost", "postage cost", "delivery fee", "tracking number", "order status", "in transit", "out for delivery", "received", "signature", "left at door", "neighbor", "mailbox", "post office", "collection", "pickup"]'),
    ('Custom Category', '[]'),
]
for category, keywords in brand_categories_keywords:
    c.execute('INSERT INTO brand_keywords (brand_id, category, keywords) VALUES (?, ?, ?)', (brand, category, keywords))

conn.commit()
conn.close()
print("Dropped and recreated brand_keywords and global_keywords, and inserted required categories with comprehensive keywords into both tables.") 